### ISSUE TITLE
Images not showing

### ISSUE THREAD

**Issue by Hoossayn** [VictorKabata/Notflix#1]
Images don't load with the error message below 

`W/Glide: Failed to find GeneratedAppGlideModule. You should include an annotationProcessor compile dependency on com.github.bumptech.glide:compiler in your application and a @GlideModule annotated AppGlideModule implementation or LibraryGlideModules will be silently ignored`

**Comment by VictorKabata** [comment]
I was unable to replicate this issue on my device. Did you have internet connection enabled on your device?

**Comment by VictorKabata** [comment]
Unable to replicate this issue
