### ISSUE TITLE
Update Kotlin and dependencies

### ISSUE THREAD

**Issue by pahill** [VictorKabata/Notflix#129]
Hi there!

Please, could you update your dependencies and Kotlin version? Your sample is on [our samples page](https://www.jetbrains.com/help/kotlin-multiplatform-dev/multiplatform-samples.html) and we'd love it if you could keep it updated.

Thank you so much,
Pamela
Kotlin Developer Advocate @ JetBrains

**Comment by VictorKabata** [comment]
Hi @pahill 

I'll update the dependencies as soon as possible.
