### ISSUE TITLE
Language changes is not affecting the app

### ISSUE THREAD

**Issue by peyrusse** [VictorKabata/Notflix#3]
I have changed the language to French however the sentences/presentation are still in english

PS : I have killed and relaunched the app same problem
Maybe the movies are stored on local database and not reloaded when the language changes ?

**Comment by VictorKabata** [comment]
Hello. Thank you for your feedback. The change language functionality is yet to implemented into the app.

**Comment by peyrusse** [comment]
Ok thanks for the feedback.
