### ISSUE TITLE
why RepositoryImpls are using flowOf()

### ISSUE THREAD

**Issue by periva101** [VictorKabata/Notflix#50]
_I want to thank you first, 
then I hope you answer my question, it is a question, not an issue 😃_ 

All ApiService methods are returning suspend functions 
`   
  suspend fun fetchMovieDetails(movieId: Int): MovieDetailsDto?
`

why are MovieDetailsRepositoryImpl methods had converted to` flowOf () `
e.g
```
    override suspend fun getMovieDetails(movieId: Int): Flow<MovieDetails?> {
        val networkResponse = apiService.fetchMovieDetails(movieId = movieId)

        return flowOf(networkResponse?.toDomain())
    }
```

what are the benefits of making all repo methods in kotlin flow, 
where consuming suspend fun is easier than flow?
also combing two suspend funs is much easier to combine two flows to create new usecases.

I see this pattern I would like to know the secret behind 😎

**Comment by periva101** [comment]
@VictorKabata @MartinMugambi @Kagiri11

**Comment by Kagiri11** [comment]
@periva101  this is no secret behind it. It's just that we want to expose a flow of MovieDetails from the repo layer.

**Comment by VictorKabata** [comment]
@periva101 This will make it easier to add caching later. I'm expecting whatever caching lib we decide to use will return Flow<List<Movies>> that is why we are using flowOf{} though It has no functional use at the moment.
